version: "3"

services:
  db:
    image: mysql:5.7
    container_name: raindrop_db
    environment:
      # - validate_password.policy=LOW
      # - default_password_lifetime=0
      # - validate_password.length=4
      # - validate_password.special_char_count=0
      # - validate_password.mixed_case_count=0
      # - validate_password.number_count=0
      - MYSQL_DATABASE=droptop
      - MYSQL_ROOT_PASSWORD=1234
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /home/ubuntu/raindrop/db/data:/var/lib/mysql
    networks:
      - raindrop_network

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: raindrop_app
    links:
      - db
    restart: always
    ports:
      - "80:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/droptop?characterEncoding=UTF-8&serverTimezone=UTC&&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - raindrop_network

networks:
  raindrop_network: